# Generated by Django 5.1.5 on 2025-02-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_agendamento', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
