# Generated by Django 5.1.5 on 2025-02-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_agendamento', '0005_rename_service_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duração em minutos')),
                ('category', models.CharField(choices=[('cilios', 'Cílios'), ('unha', 'Unha'), ('limpeza_pele', 'Limpeza de Pele'), ('sobrancelha', 'Sobrancelha')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_agendamento.service'),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
