# Generated by Django 5.1.5 on 2025-02-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_agendamento', '0006_service_alter_appointment_service_delete_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='application',
        ),
        migrations.AddField(
            model_name='service',
            name='maintenance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
